### ISSUE TITLE
Hamming distance example error

### ISSUE THREAD

**Issue by phuctran89** [ibarrond/Pyfhel#153] opened 2022-11-14 11:24 UTC
**Description:**
When I run file Demo_8_HammingDist.py of Hamming distance example on pyfhel, I received the contextGen() function error.

**Code To Reproduce Error**

```
A1. Vector generation
	v1 = [0 1 1 0 0 1 0 1 0 0 1 1 1 1 1 1 1 0 1 0...
	v2 = [1 0 0 1 1 0 0 1 1 1 0 0 1 1 0 0 0 1 0 0...
	vRes = 132
Traceback (most recent call last):
  File "Demo_8_HammingDist.py", line 137, in <module>
    HE = get_BFV_context_hammingDist(l, sec=128, use_n_min=True)
  File "Demo_8_HammingDist.py", line 137, in get_BFV_context_hammingDist
    context_status = HE.contextGen(**context_params)
  File "Pyfhel/Pyfhel.pyx", line 128, in Pyfhel.Pyfhel.Pyfhel.contextGen
TypeError: contextGen() takes at least 1 positional argument (0 given)
```

**Expected behavior:**
Output same as Hamming distance example result.

**Setup:**
OS: Ubuntu 20.04.5 LTS
Python: 3.8.10
C compiler version: GCC 9.4.0
Pyfhel Version: 2.2.5

What’s the error and how to fix it? @ibarrond

**Comment by ibarrond** [comment] 2022-11-14 14:51
@phuctran89 Please fill the entire Bug Report template. All the information there is essential to understand and debug the error.

**Comment by phuctran89** [comment] 2022-11-14 15:12
@ibarrond I updated full error. Thanks

**Comment by ibarrond** [comment] 2022-11-14 15:16
@phuctran89 Please fill the **entire** Bug report template:

**Description**
A clear and concise description of what the bug is. If it is related to Installation, you can skip all the sections except the setup. 

**Code To Reproduce Error**
[Well formatted python code (surrounded by triple \`\`\`).
Include the full error code in text format (don't worry about the size of the issue, but don't use screenshots! This way we can search it and reference it in the future)]

**Expected behavior**
[A clear and concise description of what you expected to happen. Can be omitted if obvious]

**Setup:**
 - OS: [e.g. Windows10, Ubuntu]
 - Python: [e.g. 3.8.6]
 - C compiler version: [e.g. MSC v.1916 64 bit (AMD64), can be easily found between brackets by running `python` in a terminal]
 - Pyfhel Version: [e.g. 2.2.5 --> If lower than latest github repo version, please try that one out first!]

**Comment by phuctran89** [comment] 2022-11-14 16:00
@ibarrond check again. Thanks

**Comment by ibarrond** [comment] 2022-11-14 16:30
@phuctran89 You are using an old version of Pyfhel (`Pyfhel==2.2.5`). I'm afraid that version is no longer supported.

Please upgrade to the latest Pyfhel version. The Hamming Distance example runs smoothly with that version.

**Comment by phuctran89** [comment] 2022-11-15 04:42
When I upgraded to pyfhel 3.3.1, the error is solved. But other codes of mine appear errors (not happen with pyfhel 2.2.5)

‘’’
from Pyfhel import Pyfhel
…
client_he = Pyfhel()
client_he.contextGen(p=65537)
client_he.keyGen()
… 

Traceback (most recent call last):
  File "client.py", line 21, in <module>
     client_he.contextGen(p=65537)
  File "Pyfhel/Pyfhel.pyx", line 194, in Pyfhel.Pyfhel.Pyfhel.contextGen
TypeError: contextGen() takes at least 2 positional arguments (0 given)
‘’’
Any idea @ibarrond. Thanks.

**Comment by phuctran89** [comment] 2022-11-15 05:11
And the other errors related to keyGen() function of pyfhel 3.3.1 (not happen with pyfhel 2.2.5)
```
from Pyfhel import Pyfhel
…
HE = Pyfhel()
KEYGEN_PARAMS = { “p”:17, “r”:1, “d”:0, “c”:2, “sec”:128, “w”:64, “L”:50, “m”:-1, “R”:3, “s”:0, “gens”:[], “ords”:[] }

HE.keyGen(KEYGEN_PARAMS)
… 

Traceback (most recent call last):
  File "client.py", line 323, in <module>
     HE.keyGen(KEYGEN_PARAMS)
TypeError: keyGen() takes at least 0 positional argument (1 given)

```

Any idea @ibarrond. Thanks.

**Comment by ibarrond** [comment] 2022-11-15 09:00
First, since the original issue is solved (there is no longer an error in the Hamming distance Demo), you should close this issue and open a new one with your other questions.

Secondly, most of the parameters you use in your functions are no longer in use. Good examples of up-to-date use of Pyfhel can be found in the `examples` folder. Feel free to open new issues if you need help with particular problems, but be sure to check the Demos with working code before that!

**Closed by ibarrond** 2022-11-15 09:00 UTC

**Comment by phuctran89** [comment] 2022-11-15 09:15
Thanks @ibarrond. Please help to delete this thread (not close) and support my new issue thread. Thanks
