### ISSUE TITLE
Executing Demo_HelloWorld.py leads to an Error

### ISSUE THREAD

**Issue by allensll** [ibarrond/Pyfhel#19] opened 2018-12-01 06:45 UTC
Hello,

I installed Pyfhel use `pip install Pyfhel` and use python3.6, then ran `Pyfhel/examples/Demo_HelloWorld.py`, but got the following error:

```
==============================================================
===================== Pyfhel HELLO WORLD =====================
==============================================================
1. Creating Context and KeyGen in a Pyfhel Object 
2. Encrypting integers
Traceback (most recent call last):
  File "Demo_HelloWorld.py", line 29, in <module>
    ctxt1 = HE.encryptInt(integer1) # Encryption makes use of the public key
  File "Pyfhel/Pyfhel.pyx", line 150, in Pyfhel.Pyfhel.Pyfhel.encryptInt
  File "Pyfhel/Pyfhel.pyx", line 168, in Pyfhel.Pyfhel.Pyfhel.encryptInt
RuntimeError: cannot resize aliased Ciphertext
```

**Comment by ibarrond** [comment] 2018-12-01 18:37
Hi @allensll , could you please share your OS? right now I can't reproduce your error. This is what I'm getting:


```
ibarrond@ibarrond:~/Pyfhel/examples$ python3 Demo_HelloWorld.py
==============================================================
===================== Pyfhel HELLO WORLD =====================
==============================================================
1. Creating Context and KeyGen in a Pyfhel Object
2. Encrypting integers
    int  127 -> ctxt1  <class 'Pyfhel.PyCtxt.PyCtxt'>
    int  -2 -> ctxt2  <class 'Pyfhel.PyCtxt.PyCtxt'>
3. Operating with encrypted integers
4. Decrypting result:
     addition:       decrypt(ctxt1 + ctxt2) =   125
     substraction:   decrypt(ctxt1 - ctxt2) =   129
     multiplication: decrypt(ctxt1 + ctxt2) =   -254
```
Just in case, I'm updating a new version to PyPi.

**Comment by allensll** [comment] 2018-12-02 01:56
> Hi @allensll , could you please share your OS? right now I can't reproduce your error. This is what I'm getting:
> 
> ```
> ibarrond@ibarrond:~/Pyfhel/examples$ python3 Demo_HelloWorld.py
> ==============================================================
> ===================== Pyfhel HELLO WORLD =====================
> ==============================================================
> 1. Creating Context and KeyGen in a Pyfhel Object
> 2. Encrypting integers
>     int  127 -> ctxt1  <class 'Pyfhel.PyCtxt.PyCtxt'>
>     int  -2 -> ctxt2  <class 'Pyfhel.PyCtxt.PyCtxt'>
> 3. Operating with encrypted integers
> 4. Decrypting result:
>      addition:       decrypt(ctxt1 + ctxt2) =   125
>      substraction:   decrypt(ctxt1 - ctxt2) =   129
>      multiplication: decrypt(ctxt1 + ctxt2) =   -254
> ```
> Just in case, I'm updating a new version to PyPi.

Hi @ibarrond , my OS is Ubuntu16.04LTS, and use anaconda env.
By the way, I use `CC=/usr/bin/gcc-6 pip install Pyfhel` to install Pyfhel, and version is 2.0.0a5

**Comment by inJeans** [comment] 2018-12-10 03:48
I am also getting the same error. 
```
==============================================================
===================== Pyfhel HELLO WORLD =====================
==============================================================
1. Creating Context and KeyGen in a Pyfhel Object
2. Encrypting integers
Traceback (most recent call last):
  File "Pyfhel/examples/Demo_HelloWorld.py", line 29, in <module>
    ctxt1 = HE.encryptInt(integer1) # Encryption makes use of the public key
  File "Pyfhel/Pyfhel.pyx", line 150, in Pyfhel.Pyfhel.Pyfhel.encryptInt
  File "Pyfhel/Pyfhel.pyx", line 168, in Pyfhel.Pyfhel.Pyfhel.encryptInt
RuntimeError: cannot resize aliased Ciphertext
```

I'm using SUSE Linux Enterprise Server 12 SP3, and Anaconda python 3.7.0. I built with the latest Pyfhel verison on PyPi (2.0.0a5). Thanks

**Comment by FranzHuebner** [comment] 2018-12-11 23:40
Hi,
I get the same error from above under Windows with Pyfhel 2.0.0a5 and I tried the older version 2.0.0a4 aswell and got the same error again. 
I manually reinstalled Cython, the library, python 3.7 and 3.6the buildtools and tried it again without success.  

Greetz

**Comment by ibarrond** [comment] 2018-12-12 08:04
I'll try to reproduce the error in a different OS (Ubuntu 18.04 and Windows 10 are working for me). 
Other than that, I have detected the piece of code that raises the exception (some internal C++ code in SEAL). Thanks for all your efforts!

**Comment by tonina** [comment] 2019-01-17 12:44
Hello.
I got exactly the same error. Windows 7, python 3.6, pyfhel 2.0.0a5.
```
Traceback (most recent call last):
  File "D:/Programming/Projects/tasks/text_to_speech/homomorphic_encryption/hel/simple_demo.py", line 29, in <module>
    ctxt1 = HE.encryptInt(integer1) # Encryption makes use of the public key
  File "Pyfhel/Pyfhel.pyx", line 150, in Pyfhel.Pyfhel.Pyfhel.encryptInt
  File "Pyfhel/Pyfhel.pyx", line 168, in Pyfhel.Pyfhel.Pyfhel.encryptInt
RuntimeError: cannot resize aliased Ciphertext
```

**Comment by Zeeshan2901** [comment] 2019-01-22 23:40
Hello.

I am getting errors while running Pyfhel/examples/Demo_HelloWorld.py.
I am using python 3.6 and Ubuntu 18.10 and pyfhel 2.0.0a5.

This is a bit different from the above errors,
 


eeshan@zeeshan:~/pyfhel/Pyfhel/examples$ python Demo_HelloWorld.py
==============================================================
===================== Pyfhel HELLO WORLD =====================
==============================================================
1. Creating Context and KeyGen in a Pyfhel Object 
2. Encrypting integers
Segmentation fault (core dumped)
zeeshan@zeeshan:~/pyfhel/Pyfhel/examples$ python2 Demo_HelloWorld.py
==============================================================
===================== Pyfhel HELLO WORLD =====================
==============================================================
1. Creating Context and KeyGen in a Pyfhel Object 
2. Encrypting integers
Segmentation fault (core dumped)
zeeshan@zeeshan:~/pyfhel/Pyfhel/examples$ python3 Demo_HelloWorld.py
Traceback (most recent call last):
  File "Demo_HelloWorld.py", line 6, in <module>
    from Pyfhel import Pyfhel, PyPtxt, PyCtxt
ModuleNotFoundError: No module named 'Pyfhel'
zeeshan@zeeshan:~/pyfhel/Pyfhel/examples$

**Comment by Zeeshan2901** [comment] 2019-01-22 23:58
Hello.

I am getting errors while running Pyfhel/examples/Demo_HelloWorld.py.
I am using python 3.6 and Ubuntu 18.10 and pyfhel 2.0.0a5.

This is a bit different from the above errors

[error.txt](https://github.com/ibarrond/Pyfhel/files/2785065/error.txt)

**Comment by ibarrond** [comment] 2019-02-01 08:33
@Zeeshan2901 That one is entirely my fault! Regarding the main error, a BugFix will take some time, since the creation of Ciphertexts needs to include a new parameter to cope with those kinds of errors.

**Comment by NilsHendrikLukas** [comment] 2019-02-07 16:12
@ibarrond Maybe you can remark in the README that the current version doesn't work. Otherwise great work. :)

**Comment by marcwil** [comment] 2019-03-12 20:17
I'll be working on a pull request that fixes this problem

**Comment by Koztov** [comment] 2019-05-05 14:57
I am having the same error. Hoping to get a fix soon. I truly appreciate the work done so far.

**Comment by charantej-config** [comment] 2019-10-27 08:01
iam getting an error in INSTALLING pyfhel
using    pip install pyfhel 
what should  i do?

**Comment by ibarrond** [comment] 2020-09-06 21:37
Unfortunately I cannot reproduce the error anymore. i tested `Demo_HelloWorld.py` using the latest version of the library both in Ubuntu18.04 and in Windows10 and it worked correctly with both. Closing. Feel free to reopen if the error reappears (but please give enough details to reproduce it!).

W.R.T. the installation, please try again now! it should be corrected.

**Closed by ibarrond** 2020-09-06 21:37 UTC
Labels: bug
